# This file was generated by GoReleaser. DO NOT EDIT.
cask "cowpoke" do
  desc "CLI tool for syncing kubeconfigs from multiple Rancher servers"
  homepage "https://github.com/imandrew/cowpoke"
  version "1.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cowpoke"

  on_macos do
    on_intel do
      url "https://github.com/imandrew/cowpoke/releases/download/v1.1.1/cowpoke_Darwin_x86_64.tar.gz"
      sha256 "395259f9f9c18f203025a8ca5640a7a1227eeadfafe7512c1bbdf91b72d2c282"
    end
    on_arm do
      url "https://github.com/imandrew/cowpoke/releases/download/v1.1.1/cowpoke_Darwin_arm64.tar.gz"
      sha256 "ca13dc3b8502f6c436852062b0b1cf2569dc71bd628512ba1f229c5c7c52f0e2"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/imandrew/cowpoke/releases/download/v1.1.1/cowpoke_Linux_x86_64.tar.gz"
      sha256 "0c2c00008c0f729af924253842ceeb3b0233218ccb61f20b65ff2afbf171ec19"
    end
    on_arm do
      url "https://github.com/imandrew/cowpoke/releases/download/v1.1.1/cowpoke_Linux_arm64.tar.gz"
      sha256 "31c1eee9434cec707a940681e330c4bf9944f733686b42a506444c0f4ec3b050"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cowpoke"]
    end
  end

  # No zap stanza required
end
