# This file was generated by GoReleaser. DO NOT EDIT.
cask "cowpoke" do
  desc "CLI tool for syncing kubeconfigs from multiple Rancher servers"
  homepage "https://github.com/imandrew/cowpoke"
  version "1.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cowpoke"

  on_macos do
    on_intel do
      url "https://github.com/imandrew/cowpoke/releases/download/v1.1.0/cowpoke_Darwin_x86_64.tar.gz"
      sha256 "7423f62552c9990cbc25c4dc45c9378c7258ca89da0f8ca3e3ffc598364081ce"
    end
    on_arm do
      url "https://github.com/imandrew/cowpoke/releases/download/v1.1.0/cowpoke_Darwin_arm64.tar.gz"
      sha256 "b8d55666945aa04d3a270edb3e95d2a639b39989a80442c6517ac6d70cd1d1ec"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/imandrew/cowpoke/releases/download/v1.1.0/cowpoke_Linux_x86_64.tar.gz"
      sha256 "c785aed4dc736cf7c42cfd528152e095ed4109f613cd2bb500ed7072febfc0b0"
    end
    on_arm do
      url "https://github.com/imandrew/cowpoke/releases/download/v1.1.0/cowpoke_Linux_arm64.tar.gz"
      sha256 "3a60861d50469f3f551801c241f8576c808c978c938b439119316bc0f79d9e93"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cowpoke"]
    end
  end

  # No zap stanza required
end
