# This file was generated by GoReleaser. DO NOT EDIT.
cask "cowpoke" do
  desc "CLI tool for syncing kubeconfigs from multiple Rancher servers"
  homepage "https://github.com/imandrew/cowpoke"
  version "1.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cowpoke"

  on_macos do
    on_intel do
      url "https://github.com/imandrew/cowpoke/releases/download/v1.0.0/cowpoke_Darwin_x86_64.tar.gz"
      sha256 "9bf4661168a9079d0804f82ff20f51f37b95a20ec539307188b63bc7c3b66995"
    end
    on_arm do
      url "https://github.com/imandrew/cowpoke/releases/download/v1.0.0/cowpoke_Darwin_arm64.tar.gz"
      sha256 "f8da814330c93ac65f9ae41ebeafba72cb34ba14c65d27bb5e9f4ba147cb6601"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/imandrew/cowpoke/releases/download/v1.0.0/cowpoke_Linux_x86_64.tar.gz"
      sha256 "ca6dcaa4c516b401c7807fbe211dfbe2dbbdad6f531773d82131c74bae6ccc7f"
    end
    on_arm do
      url "https://github.com/imandrew/cowpoke/releases/download/v1.0.0/cowpoke_Linux_arm64.tar.gz"
      sha256 "fdec3f0453773c4e8c53d57b4afb8402737b1161138c92f57bc5cf44a3f621fc"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cowpoke"]
    end
  end

  # No zap stanza required
end
